CREATE TABLE IF NOT EXISTS shopping_list (
    item_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name TEXT NOT NULL,
    price decimal(10,2) NOT NULL,
    category grocery NOT NULL,
    checked BOOLEAN DEFAULT FALSE,
    date_added TIMESTAMP DEFAULT now() NOT NULL    
);

DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery AS ENUM (
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);

